### PR TITLE
Investigator group page

### PR DESCRIPTION
**Pull request by lionasp**
New PR instead of https://github.com/Impactstory/impactstory-tng/pull/21

### CODE REVIEW

**Comment by Shotgunosine** [comment]
Hi @hpiwowar and @jasonpriem, we asked @lionasp to create this PR to implement a group view page for us. This PR allows a request to /g/... to specify a group name, the individual ids that should be included in the group view,  a url for the group's logo, and the achievements to aggregate. We've got an instance running of an AWS box where you can see an example:
(http://54.174.178.216:5000/g/NIMH%20Intramural%20Research%20Program/?persons=0000-0003-4613-6643&persons=0000-0002-5352-7338&logo_url=https:%2F%2Fcmn.nimh.nih.gov%2Fstatic%2Fimg%2Fnih-nimh-logo.png&achievements=percent_fulltext)

If you merge this PR, we'll be able to use this interface to create a page summarizing the NIMH intramural research program's open science performance. Once we can start publicizing these scores, we can begin moving investigators towards adopting open science practices.

**Comment by jasonpriem** [comment]
Tried the example URL; got "54.174.178.216 refused to connect."

**Comment by Shotgunosine** [comment]
Whoops, sorry about that, give it another try.

**Comment by peterdesmet** [comment]
Is this functional?

Tried it with https://profiles.impactstory.org/g/INBO/?persons=0000-0002-8442-8025&persons=0000-0001-7268-4200&logo_url=https%2F%2Flifewatch.inbo.be%2Fblog%2Ftheme%2Fimg%2Finbo-logo.png&achievements=percent_fulltext but got "page does not exist"

**Comment by jasonpriem** [comment]
We gave it a shot but no it's not functioning right now. Looks like some bugs associated with database calls being slow on the production database (which is, I'm guessing, larger than the one used to test this). We're looking into it further. Will have more updates later.

**Pull request merged**
